In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date' : pd.date_range('2026-01-01', periods=20),
    'Product' : ['A', 'B', 'C', 'D'] * 5,
    'Region' : ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 
                'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales' : np.random.randint(100, 1000, 20),
    'Units' : np.random.randint(10, 100, 20),
    'Rep' : ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 
             'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [3]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2026-01-01       A   East    602     67   John  January      Q1
1  2026-01-02       B   West    358     51   Mary  January      Q1
2  2026-01-03       C  North    638     32    Bob  January      Q1
3  2026-01-04       D  South    331     14  Alice  January      Q1
4  2026-01-05       A   East    728     56   John  January      Q1
5  2026-01-06       B   West    925     98   Mary  January      Q1
6  2026-01-07       C  North    832     53    Bob  January      Q1
7  2026-01-08       D  South    422     19  Alice  January      Q1
8  2026-01-09       A   East    373     32   John  January      Q1
9  2026-01-10       B   West    919     42   Mary  January      Q1
10 2026-01-11       C  North    701     64    Bob  January      Q1
11 2026-01-12       D  South    660     26  Alice  January      Q1
12 2026-01-13       A   East    502     59   John  January      Q1
13 2026-01-14       B   West    736     70   Mary  January      Q1
14 2026-01-15       C  North    990     73    Bob  January      Q1
15 2026-01-16       D  South    910     43  Alice  January      Q1
16 2026-01-17       A   East    454     40   John  January      Q1
17 2026-01-18       B   West    138     73   Mary  January      Q1
18 2026-01-19       C  North    401     93    Bob  January      Q1
19 2026-01-20       D  South    465     94  Alice  January      Q1

In [4]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     502.0    NaN    NaN    NaN
North      NaN    NaN  701.0    NaN
South      NaN    NaN    NaN  465.0
West       NaN  736.0    NaN    NaN

In [5]:
pivot2 = pd.pivot_table(df, values = ['Sales', 'Units'], index='Region', columns='Product')
print('\nPivot Table with multiple values : ')
pivot2

Pivot Table with multiple values :

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     531.8    NaN    NaN    NaN  50.8   NaN   NaN   NaN
North      NaN    NaN  712.4    NaN   NaN   NaN  63.0   NaN
South      NaN    NaN    NaN  557.6   NaN   NaN   NaN  39.2
West       NaN  615.2    NaN    NaN   NaN  66.8   NaN   NaN

In [7]:
pd.crosstab(df['Region'], df['Product']) # tells the count of region and product combination

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0